// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuzvslfoacakgdnnooep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1enZzbGZvYWNha2dkbm5vb2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDYzODAsImV4cCI6MjA2OTgyMjM4MH0.wx39wBXBbpf_ADapqCtQk3PsJE5jvAs9EtbJk9wADfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});